use std::path::PathBuf;

use anyhow::Result;

use super::plugin_adapter::{
    plugin_adapter_install_smoke, plugin_adapter_install_smoke_observer_bundle,
    plugin_adapter_install_smoke_verify, plugin_adapter_observer_bundle, plugin_adapter_scaffold,
    plugin_adapter_scaffold_verify, plugin_clean_package_operator_index,
    plugin_control_plane_fixture_handoff, plugin_control_plane_fixture_handoff_verify,
    plugin_distribution_observer_bundle, plugin_packaged_replacement_observer_bundle,
    plugin_packaged_replacement_observer_bundle_verify,
    plugin_release_gate_with_replacement_observer_bundle,
};
use super::plugin_consumer::{
    plugin_consumer_lifecycle, plugin_consumer_lifecycle_observer_bundle,
    plugin_consumer_lifecycle_observer_bundle_verify, plugin_consumer_lifecycle_windows_recovery,
};
use super::plugin_distribution::{
    plugin_distribution_rehearsal, plugin_install_smoke, plugin_manifest, plugin_manifest_verify,
    plugin_package, plugin_package_verify, plugin_readiness, PluginDistributionRehearsalOptions,
    PluginInstallSmokeOptions, PluginManifestVerifyOptions, PluginPackageOptions,
    PluginPackageVerifyOptions,
};
use super::plugin_pulse::{
    plugin_pulse_apply_observer_bundle, plugin_pulse_apply_observer_bundle_verify,
    plugin_pulse_apply_windows_recovery, plugin_pulse_chain_observer_bundle,
    plugin_pulse_chain_observer_bundle_verify, plugin_pulse_eval_loop_observer_bundle,
    plugin_pulse_eval_loop_observer_bundle_verify, plugin_pulse_executor_observer_bundle,
    plugin_pulse_executor_observer_bundle_verify, plugin_pulse_once_observer_bundle,
    plugin_pulse_once_observer_bundle_verify,
};
use super::plugin_release::{
    plugin_final_install_transcript, plugin_final_install_transcript_observer_bundle,
    plugin_release_candidate, plugin_release_candidate_control_plane_fixture_handoff,
    plugin_release_candidate_control_plane_fixture_handoff_verify,
    plugin_release_candidate_observer_bundle, plugin_release_candidate_observer_bundle_verify,
    plugin_release_candidate_verify, plugin_release_candidate_windows_recovery,
    plugin_release_candidate_windows_recovery_verify,
    plugin_release_candidate_windows_transfer_bundle, plugin_shipment_readiness,
};
use super::{plugin_wrapper_harness, plugin_wrapper_harness_verify, PluginCommand};

pub(super) fn plugin(command: PluginCommand) -> Result<()> {
    match command {
        PluginCommand::Readiness { out, json } => plugin_readiness(out, json),
        PluginCommand::Manifest { out_dir, json } => plugin_manifest(out_dir, json),
        PluginCommand::ManifestVerify {
            manifest_dir,
            manifest_sha256,
            json,
        } => plugin_manifest_verify(PluginManifestVerifyOptions {
            manifest_dir,
            manifest_sha256,
            json_output: json,
        }),
        PluginCommand::InstallSmoke {
            manifest_dir,
            verification,
            verification_sha256,
            out,
            json,
        } => plugin_install_smoke(PluginInstallSmokeOptions {
            manifest_dir,
            verification,
            verification_sha256,
            out,
            json_output: json,
        }),
        PluginCommand::Package {
            manifest_dir,
            manifest_verification,
            manifest_verification_sha256,
            install_smoke,
            install_smoke_sha256,
            out_dir,
            json,
        } => plugin_package(PluginPackageOptions {
            manifest_dir,
            manifest_verification,
            manifest_verification_sha256,
            install_smoke,
            install_smoke_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::PackageVerify {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            json,
        } => plugin_package_verify(PluginPackageVerifyOptions {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            json_output: json,
        }),
        PluginCommand::DistributionRehearsal {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            out_dir,
            json,
        } => plugin_distribution_rehearsal(PluginDistributionRehearsalOptions {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::ConsumerLifecycle {
            package_summary,
            package_summary_sha256,
            package_archive,
            package_archive_sha256,
            adapter_scaffold,
            adapter_scaffold_sha256,
            out_dir,
            json,
        } => plugin_consumer_lifecycle(PluginConsumerLifecycleOptions {
            package_summary,
            package_summary_sha256,
            package_archive,
            package_archive_sha256,
            adapter_scaffold,
            adapter_scaffold_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::ConsumerLifecycleWindowsRecovery {
            package_summary,
            package_summary_sha256,
            package_archive,
            package_archive_sha256,
            adapter_scaffold,
            adapter_scaffold_sha256,
            out_dir,
            json,
        } => plugin_consumer_lifecycle_windows_recovery(
            PluginConsumerLifecycleWindowsRecoveryOptions {
                package_summary,
                package_summary_sha256,
                package_archive,
                package_archive_sha256,
                adapter_scaffold,
                adapter_scaffold_sha256,
                out_dir,
                json_output: json,
            },
        ),
        PluginCommand::ConsumerLifecycleObserverBundle {
            macos_lifecycle,
            macos_sha256,
            ubuntu_lifecycle,
            ubuntu_sha256,
            windows_lifecycle,
            windows_sha256,
            out_dir,
            json,
        } => plugin_consumer_lifecycle_observer_bundle(
            PluginConsumerLifecycleObserverBundleOptions {
                macos_lifecycle,
                macos_sha256,
                ubuntu_lifecycle,
                ubuntu_sha256,
                windows_lifecycle,
                windows_sha256,
                out_dir,
                json_output: json,
            },
        ),
        PluginCommand::ConsumerLifecycleObserverBundleVerify {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            json,
        } => plugin_consumer_lifecycle_observer_bundle_verify(
            PluginConsumerLifecycleObserverBundleVerifyOptions {
                summary,
                summary_sha256,
                archive,
                archive_sha256,
                json_output: json,
            },
        ),
        PluginCommand::ReleaseCandidate {
            package_summary,
            package_summary_sha256,
            package_archive,
            package_archive_sha256,
            distribution_rehearsal,
            distribution_rehearsal_sha256,
            adapter_observer_bundle,
            adapter_observer_bundle_sha256,
            adapter_observer_archive,
            adapter_observer_archive_sha256,
            adapter_install_smoke_observer_bundle,
            adapter_install_smoke_observer_bundle_sha256,
            adapter_install_smoke_observer_archive,
            adapter_install_smoke_observer_archive_sha256,
            consumer_lifecycle_observer_bundle,
            consumer_lifecycle_observer_bundle_sha256,
            consumer_lifecycle_observer_archive,
            consumer_lifecycle_observer_archive_sha256,
            release_gate_with_replacement_observer_bundle,
            release_gate_with_replacement_observer_bundle_sha256,
            release_gate_with_replacement_observer_archive,
            release_gate_with_replacement_observer_archive_sha256,
            control_plane_fixture_handoff_verification,
            control_plane_fixture_handoff_verification_sha256,
            control_plane_readback_commit,
            out_dir,
            json,
        } => plugin_release_candidate(PluginReleaseCandidateOptions {
            package_summary,
            package_summary_sha256,
            package_archive,
            package_archive_sha256,
            distribution_rehearsal,
            distribution_rehearsal_sha256,
            adapter_observer_bundle,
            adapter_observer_bundle_sha256,
            adapter_observer_archive,
            adapter_observer_archive_sha256,
            adapter_install_smoke_observer_bundle,
            adapter_install_smoke_observer_bundle_sha256,
            adapter_install_smoke_observer_archive,
            adapter_install_smoke_observer_archive_sha256,
            consumer_lifecycle_observer_bundle,
            consumer_lifecycle_observer_bundle_sha256,
            consumer_lifecycle_observer_archive,
            consumer_lifecycle_observer_archive_sha256,
            release_gate_with_replacement_observer_bundle,
            release_gate_with_replacement_observer_bundle_sha256,
            release_gate_with_replacement_observer_archive,
            release_gate_with_replacement_observer_archive_sha256,
            control_plane_fixture_handoff_verification,
            control_plane_fixture_handoff_verification_sha256,
            control_plane_readback_commit,
            out_dir,
            json_output: json,
        }),
        PluginCommand::ReleaseCandidateVerify {
            summary,
            summary_sha256,
            json,
        } => plugin_release_candidate_verify(PluginReleaseCandidateVerifyOptions {
            summary,
            summary_sha256,
            json_output: json,
        }),
        PluginCommand::ReleaseCandidateWindowsRecovery {
            package_summary,
            package_summary_sha256,
            package_archive,
            package_archive_sha256,
            distribution_rehearsal,
            distribution_rehearsal_sha256,
            adapter_observer_bundle,
            adapter_observer_bundle_sha256,
            adapter_observer_archive,
            adapter_observer_archive_sha256,
            adapter_install_smoke_observer_bundle,
            adapter_install_smoke_observer_bundle_sha256,
            adapter_install_smoke_observer_archive,
            adapter_install_smoke_observer_archive_sha256,
            consumer_lifecycle_observer_bundle,
            consumer_lifecycle_observer_bundle_sha256,
            consumer_lifecycle_observer_archive,
            consumer_lifecycle_observer_archive_sha256,
            release_gate_with_replacement_observer_bundle,
            release_gate_with_replacement_observer_bundle_sha256,
            release_gate_with_replacement_observer_archive,
            release_gate_with_replacement_observer_archive_sha256,
            control_plane_fixture_handoff_verification,
            control_plane_fixture_handoff_verification_sha256,
            control_plane_readback_commit,
            out_dir,
            json,
        } => plugin_release_candidate_windows_recovery(
            PluginReleaseCandidateWindowsRecoveryOptions {
                package_summary,
                package_summary_sha256,
                package_archive,
                package_archive_sha256,
                distribution_rehearsal,
                distribution_rehearsal_sha256,
                adapter_observer_bundle,
                adapter_observer_bundle_sha256,
                adapter_observer_archive,
                adapter_observer_archive_sha256,
                adapter_install_smoke_observer_bundle,
                adapter_install_smoke_observer_bundle_sha256,
                adapter_install_smoke_observer_archive,
                adapter_install_smoke_observer_archive_sha256,
                consumer_lifecycle_observer_bundle,
                consumer_lifecycle_observer_bundle_sha256,
                consumer_lifecycle_observer_archive,
                consumer_lifecycle_observer_archive_sha256,
                release_gate_with_replacement_observer_bundle,
                release_gate_with_replacement_observer_bundle_sha256,
                release_gate_with_replacement_observer_archive,
                release_gate_with_replacement_observer_archive_sha256,
                control_plane_fixture_handoff_verification,
                control_plane_fixture_handoff_verification_sha256,
                control_plane_readback_commit,
                out_dir,
                json_output: json,
            },
        ),
        PluginCommand::ReleaseCandidateWindowsRecoveryVerify {
            recovery,
            recovery_sha256,
            out,
            json,
        } => plugin_release_candidate_windows_recovery_verify(
            PluginReleaseCandidateWindowsRecoveryVerifyOptions {
                recovery,
                recovery_sha256,
                out,
                json_output: json,
            },
        ),
        PluginCommand::ReleaseCandidateWindowsTransferBundle {
            ao2_source_archive,
            ao2_source_archive_sha256,
            recovery_dir,
            recovery,
            recovery_sha256,
            recovery_verification,
            recovery_verification_sha256,
            out_dir,
            json,
        } => plugin_release_candidate_windows_transfer_bundle(
            PluginReleaseCandidateWindowsTransferBundleOptions {
                ao2_source_archive,
                ao2_source_archive_sha256,
                recovery_dir,
                recovery,
                recovery_sha256,
                recovery_verification,
                recovery_verification_sha256,
                out_dir,
                json_output: json,
            },
        ),
        PluginCommand::ReleaseCandidateObserverBundle {
            macos_verification,
            macos_sha256,
            ubuntu_verification,
            ubuntu_sha256,
            windows_verification,
            windows_sha256,
            out_dir,
            json,
        } => {
            plugin_release_candidate_observer_bundle(PluginReleaseCandidateObserverBundleOptions {
                macos_verification,
                macos_sha256,
                ubuntu_verification,
                ubuntu_sha256,
                windows_verification,
                windows_sha256,
                out_dir,
                json_output: json,
            })
        }
        PluginCommand::ReleaseCandidateObserverBundleVerify {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            json,
        } => plugin_release_candidate_observer_bundle_verify(
            PluginReleaseCandidateObserverBundleVerifyOptions {
                summary,
                summary_sha256,
                archive,
                archive_sha256,
                json_output: json,
            },
        ),
        PluginCommand::PulseApplyObserverBundle {
            macos_apply_result,
            macos_sha256,
            ubuntu_apply_result,
            ubuntu_sha256,
            windows_apply_result,
            windows_sha256,
            windows_unavailable_reason,
            out_dir,
            json,
        } => plugin_pulse_apply_observer_bundle(PluginPulseApplyObserverBundleOptions {
            macos_apply_result,
            macos_sha256,
            ubuntu_apply_result,
            ubuntu_sha256,
            windows_apply_result,
            windows_sha256,
            windows_unavailable_reason,
            out_dir,
            json_output: json,
        }),
        PluginCommand::PulseApplyObserverBundleVerify {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            json,
        } => {
            plugin_pulse_apply_observer_bundle_verify(PluginPulseApplyObserverBundleVerifyOptions {
                summary,
                summary_sha256,
                archive,
                archive_sha256,
                json_output: json,
            })
        }
        PluginCommand::PulseOnceObserverBundle {
            macos_once,
            macos_sha256,
            ubuntu_once,
            ubuntu_sha256,
            windows_once,
            windows_sha256,
            out_dir,
            json,
        } => plugin_pulse_once_observer_bundle(PluginPulseOnceObserverBundleOptions {
            macos_once,
            macos_sha256,
            ubuntu_once,
            ubuntu_sha256,
            windows_once,
            windows_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::PulseOnceObserverBundleVerify {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            json,
        } => plugin_pulse_once_observer_bundle_verify(PluginPulseOnceObserverBundleVerifyOptions {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            json_output: json,
        }),
        PluginCommand::PulseChainObserverBundle {
            macos_chain,
            macos_sha256,
            ubuntu_chain,
            ubuntu_sha256,
            windows_chain,
            windows_sha256,
            out_dir,
            json,
        } => plugin_pulse_chain_observer_bundle(PluginPulseChainObserverBundleOptions {
            macos_chain,
            macos_sha256,
            ubuntu_chain,
            ubuntu_sha256,
            windows_chain,
            windows_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::PulseChainObserverBundleVerify {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            json,
        } => {
            plugin_pulse_chain_observer_bundle_verify(PluginPulseChainObserverBundleVerifyOptions {
                summary,
                summary_sha256,
                archive,
                archive_sha256,
                json_output: json,
            })
        }
        PluginCommand::PulseEvalLoopObserverBundle {
            macos_eval_loop,
            macos_sha256,
            ubuntu_eval_loop,
            ubuntu_sha256,
            windows_eval_loop,
            windows_sha256,
            out_dir,
            json,
        } => plugin_pulse_eval_loop_observer_bundle(PluginPulseEvalLoopObserverBundleOptions {
            macos_eval_loop,
            macos_sha256,
            ubuntu_eval_loop,
            ubuntu_sha256,
            windows_eval_loop,
            windows_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::PulseEvalLoopObserverBundleVerify {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            json,
        } => plugin_pulse_eval_loop_observer_bundle_verify(
            PluginPulseEvalLoopObserverBundleVerifyOptions {
                summary,
                summary_sha256,
                archive,
                archive_sha256,
                json_output: json,
            },
        ),
        PluginCommand::PulseExecutorObserverBundle {
            macos_executor,
            macos_sha256,
            ubuntu_executor,
            ubuntu_sha256,
            windows_executor,
            windows_sha256,
            out_dir,
            json,
        } => plugin_pulse_executor_observer_bundle(PluginPulseExecutorObserverBundleOptions {
            macos_executor,
            macos_sha256,
            ubuntu_executor,
            ubuntu_sha256,
            windows_executor,
            windows_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::PulseExecutorObserverBundleVerify {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            json,
        } => plugin_pulse_executor_observer_bundle_verify(
            PluginPulseExecutorObserverBundleVerifyOptions {
                summary,
                summary_sha256,
                archive,
                archive_sha256,
                json_output: json,
            },
        ),
        PluginCommand::PulseApplyWindowsRecovery {
            apply_result,
            apply_result_sha256,
            observer_bundle,
            observer_bundle_sha256,
            observer_archive,
            observer_archive_sha256,
            out_dir,
            json,
        } => plugin_pulse_apply_windows_recovery(PluginPulseApplyWindowsRecoveryOptions {
            apply_result,
            apply_result_sha256,
            observer_bundle,
            observer_bundle_sha256,
            observer_archive,
            observer_archive_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::ReleaseCandidateControlPlaneFixtureHandoff {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            out_dir,
            json,
        } => plugin_release_candidate_control_plane_fixture_handoff(
            PluginReleaseCandidateControlPlaneFixtureHandoffOptions {
                summary,
                summary_sha256,
                archive,
                archive_sha256,
                out_dir,
                json_output: json,
            },
        ),
        PluginCommand::ReleaseCandidateControlPlaneFixtureHandoffVerify {
            handoff,
            handoff_sha256,
            out,
            json,
        } => plugin_release_candidate_control_plane_fixture_handoff_verify(
            PluginReleaseCandidateControlPlaneFixtureHandoffVerifyOptions {
                handoff,
                handoff_sha256,
                out,
                json_output: json,
            },
        ),
        PluginCommand::FinalInstallTranscript {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            out_dir,
            json,
        } => plugin_final_install_transcript(PluginFinalInstallTranscriptOptions {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::FinalInstallTranscriptObserverBundle {
            macos_codex_transcript,
            macos_codex_sha256,
            macos_claude_transcript,
            macos_claude_sha256,
            ubuntu_codex_transcript,
            ubuntu_codex_sha256,
            ubuntu_claude_transcript,
            ubuntu_claude_sha256,
            windows_codex_transcript,
            windows_codex_sha256,
            windows_claude_transcript,
            windows_claude_sha256,
            out_dir,
            json,
        } => plugin_final_install_transcript_observer_bundle(
            PluginFinalInstallTranscriptObserverBundleOptions {
                macos_codex_transcript,
                macos_codex_sha256,
                macos_claude_transcript,
                macos_claude_sha256,
                ubuntu_codex_transcript,
                ubuntu_codex_sha256,
                ubuntu_claude_transcript,
                ubuntu_claude_sha256,
                windows_codex_transcript,
                windows_codex_sha256,
                windows_claude_transcript,
                windows_claude_sha256,
                out_dir,
                json_output: json,
            },
        ),
        PluginCommand::ShipmentReadiness {
            package_summary,
            package_summary_sha256,
            package_archive,
            package_archive_sha256,
            adapter_observer_bundle,
            adapter_observer_bundle_sha256,
            adapter_observer_archive,
            adapter_observer_archive_sha256,
            adapter_install_smoke_observer_bundle,
            adapter_install_smoke_observer_bundle_sha256,
            adapter_install_smoke_observer_archive,
            adapter_install_smoke_observer_archive_sha256,
            consumer_lifecycle_observer_bundle,
            consumer_lifecycle_observer_bundle_sha256,
            consumer_lifecycle_observer_archive,
            consumer_lifecycle_observer_archive_sha256,
            release_candidate_observer_bundle,
            release_candidate_observer_bundle_sha256,
            release_candidate_observer_archive,
            release_candidate_observer_archive_sha256,
            final_install_transcript_observer_bundle,
            final_install_transcript_observer_bundle_sha256,
            final_install_transcript_observer_archive,
            final_install_transcript_observer_archive_sha256,
            control_plane_readback_commit,
            out_dir,
            json,
        } => plugin_shipment_readiness(PluginShipmentReadinessOptions {
            package_summary,
            package_summary_sha256,
            package_archive,
            package_archive_sha256,
            adapter_observer_bundle,
            adapter_observer_bundle_sha256,
            adapter_observer_archive,
            adapter_observer_archive_sha256,
            adapter_install_smoke_observer_bundle,
            adapter_install_smoke_observer_bundle_sha256,
            adapter_install_smoke_observer_archive,
            adapter_install_smoke_observer_archive_sha256,
            consumer_lifecycle_observer_bundle,
            consumer_lifecycle_observer_bundle_sha256,
            consumer_lifecycle_observer_archive,
            consumer_lifecycle_observer_archive_sha256,
            release_candidate_observer_bundle,
            release_candidate_observer_bundle_sha256,
            release_candidate_observer_archive,
            release_candidate_observer_archive_sha256,
            final_install_transcript_observer_bundle,
            final_install_transcript_observer_bundle_sha256,
            final_install_transcript_observer_archive,
            final_install_transcript_observer_archive_sha256,
            control_plane_readback_commit,
            out_dir,
            json_output: json,
        }),
        PluginCommand::ControlPlaneFixtureHandoff {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            out_dir,
            json,
        } => plugin_control_plane_fixture_handoff(PluginControlPlaneFixtureHandoffOptions {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::ControlPlaneFixtureHandoffVerify {
            handoff,
            handoff_sha256,
            out,
            json,
        } => plugin_control_plane_fixture_handoff_verify(
            PluginControlPlaneFixtureHandoffVerifyOptions {
                handoff,
                handoff_sha256,
                out,
                json_output: json,
            },
        ),
        PluginCommand::DistributionObserverBundle {
            macos_observer,
            macos_sha256,
            ubuntu_observer,
            ubuntu_sha256,
            windows_observer,
            windows_sha256,
            out_dir,
            json,
        } => plugin_distribution_observer_bundle(PluginDistributionObserverBundleOptions {
            macos_observer,
            macos_sha256,
            ubuntu_observer,
            ubuntu_sha256,
            windows_observer,
            windows_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::CleanPackageOperatorIndex {
            macos_rehearsal,
            macos_sha256,
            ubuntu_rehearsal,
            ubuntu_sha256,
            windows_rehearsal,
            windows_sha256,
            out_dir,
            json,
        } => plugin_clean_package_operator_index(PluginCleanPackageOperatorIndexOptions {
            macos_rehearsal,
            macos_sha256,
            ubuntu_rehearsal,
            ubuntu_sha256,
            windows_rehearsal,
            windows_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::PackagedReplacementObserverBundle {
            macos_proof,
            macos_sha256,
            ubuntu_proof,
            ubuntu_sha256,
            windows_proof,
            windows_sha256,
            out_dir,
            json,
        } => plugin_packaged_replacement_observer_bundle(
            PluginPackagedReplacementObserverBundleOptions {
                macos_proof,
                macos_sha256,
                ubuntu_proof,
                ubuntu_sha256,
                windows_proof,
                windows_sha256,
                out_dir,
                json_output: json,
            },
        ),
        PluginCommand::PackagedReplacementObserverBundleVerify {
            summary,
            summary_sha256,
            archive,
            archive_sha256,
            json,
        } => plugin_packaged_replacement_observer_bundle_verify(
            PluginPackagedReplacementObserverBundleVerifyOptions {
                summary,
                summary_sha256,
                archive,
                archive_sha256,
                json_output: json,
            },
        ),
        PluginCommand::ReleaseGateWithReplacementObserverBundle {
            macos_rollup,
            macos_sha256,
            ubuntu_rollup,
            ubuntu_sha256,
            windows_rollup,
            windows_sha256,
            out_dir,
            json,
        } => plugin_release_gate_with_replacement_observer_bundle(
            PluginReleaseGateWithReplacementObserverBundleOptions {
                macos_rollup,
                macos_sha256,
                ubuntu_rollup,
                ubuntu_sha256,
                windows_rollup,
                windows_sha256,
                out_dir,
                json_output: json,
            },
        ),
        PluginCommand::AdapterScaffold {
            package_summary,
            package_summary_sha256,
            package_archive,
            package_archive_sha256,
            k37_bundle,
            k37_bundle_sha256,
            k37_archive,
            k37_archive_sha256,
            out_dir,
            json,
        } => plugin_adapter_scaffold(PluginAdapterScaffoldOptions {
            package_summary,
            package_summary_sha256,
            package_archive,
            package_archive_sha256,
            k37_bundle,
            k37_bundle_sha256,
            k37_archive,
            k37_archive_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::AdapterScaffoldVerify {
            summary,
            summary_sha256,
            json,
        } => plugin_adapter_scaffold_verify(PluginAdapterScaffoldVerifyOptions {
            summary,
            summary_sha256,
            json_output: json,
        }),
        PluginCommand::AdapterInstallSmoke {
            summary,
            summary_sha256,
            out,
            json,
        } => plugin_adapter_install_smoke(PluginAdapterInstallSmokeOptions {
            summary,
            summary_sha256,
            out,
            json_output: json,
        }),
        PluginCommand::AdapterInstallSmokeVerify {
            smoke,
            smoke_sha256,
            json,
        } => plugin_adapter_install_smoke_verify(PluginAdapterInstallSmokeVerifyOptions {
            smoke,
            smoke_sha256,
            json_output: json,
        }),
        PluginCommand::AdapterInstallSmokeObserverBundle {
            macos_verification,
            macos_sha256,
            ubuntu_verification,
            ubuntu_sha256,
            windows_verification,
            windows_sha256,
            out_dir,
            json,
        } => plugin_adapter_install_smoke_observer_bundle(
            PluginAdapterInstallSmokeObserverBundleOptions {
                macos_verification,
                macos_sha256,
                ubuntu_verification,
                ubuntu_sha256,
                windows_verification,
                windows_sha256,
                out_dir,
                json_output: json,
            },
        ),
        PluginCommand::AdapterObserverBundle {
            macos_verification,
            macos_sha256,
            ubuntu_verification,
            ubuntu_sha256,
            windows_verification,
            windows_sha256,
            out_dir,
            json,
        } => plugin_adapter_observer_bundle(PluginAdapterObserverBundleOptions {
            macos_verification,
            macos_sha256,
            ubuntu_verification,
            ubuntu_sha256,
            windows_verification,
            windows_sha256,
            out_dir,
            json_output: json,
        }),
        PluginCommand::WrapperHarness {
            readiness,
            readiness_sha256,
            args_file,
            args_sha256,
            run_kind,
            out_dir,
            json,
        } => plugin_wrapper_harness(PluginWrapperHarnessOptions {
            readiness,
            readiness_sha256,
            args_file,
            args_sha256,
            run_kind,
            out_dir,
            json_output: json,
        }),
        PluginCommand::WrapperHarnessVerify {
            evidence_dir,
            summary_sha256,
            json,
        } => plugin_wrapper_harness_verify(PluginWrapperHarnessVerifyOptions {
            evidence_dir,
            summary_sha256,
            json_output: json,
        }),
    }
}

pub(super) struct PluginWrapperHarnessOptions {
    pub(super) readiness: PathBuf,
    pub(super) readiness_sha256: String,
    pub(super) args_file: PathBuf,
    pub(super) args_sha256: String,
    pub(super) run_kind: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginConsumerLifecycleOptions {
    pub(super) package_summary: PathBuf,
    pub(super) package_summary_sha256: String,
    pub(super) package_archive: PathBuf,
    pub(super) package_archive_sha256: String,
    pub(super) adapter_scaffold: PathBuf,
    pub(super) adapter_scaffold_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginConsumerLifecycleWindowsRecoveryOptions {
    pub(super) package_summary: PathBuf,
    pub(super) package_summary_sha256: String,
    pub(super) package_archive: PathBuf,
    pub(super) package_archive_sha256: String,
    pub(super) adapter_scaffold: PathBuf,
    pub(super) adapter_scaffold_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginConsumerLifecycleObserverBundleOptions {
    pub(super) macos_lifecycle: PathBuf,
    pub(super) macos_sha256: String,
    pub(super) ubuntu_lifecycle: PathBuf,
    pub(super) ubuntu_sha256: String,
    pub(super) windows_lifecycle: PathBuf,
    pub(super) windows_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginConsumerLifecycleObserverBundleVerifyOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) archive: PathBuf,
    pub(super) archive_sha256: String,
    pub(super) json_output: bool,
}

pub(super) struct PluginReleaseCandidateOptions {
    pub(super) package_summary: PathBuf,
    pub(super) package_summary_sha256: String,
    pub(super) package_archive: PathBuf,
    pub(super) package_archive_sha256: String,
    pub(super) distribution_rehearsal: PathBuf,
    pub(super) distribution_rehearsal_sha256: String,
    pub(super) adapter_observer_bundle: PathBuf,
    pub(super) adapter_observer_bundle_sha256: String,
    pub(super) adapter_observer_archive: PathBuf,
    pub(super) adapter_observer_archive_sha256: String,
    pub(super) adapter_install_smoke_observer_bundle: PathBuf,
    pub(super) adapter_install_smoke_observer_bundle_sha256: String,
    pub(super) adapter_install_smoke_observer_archive: PathBuf,
    pub(super) adapter_install_smoke_observer_archive_sha256: String,
    pub(super) consumer_lifecycle_observer_bundle: PathBuf,
    pub(super) consumer_lifecycle_observer_bundle_sha256: String,
    pub(super) consumer_lifecycle_observer_archive: PathBuf,
    pub(super) consumer_lifecycle_observer_archive_sha256: String,
    pub(super) release_gate_with_replacement_observer_bundle: PathBuf,
    pub(super) release_gate_with_replacement_observer_bundle_sha256: String,
    pub(super) release_gate_with_replacement_observer_archive: PathBuf,
    pub(super) release_gate_with_replacement_observer_archive_sha256: String,
    pub(super) control_plane_fixture_handoff_verification: PathBuf,
    pub(super) control_plane_fixture_handoff_verification_sha256: String,
    pub(super) control_plane_readback_commit: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginReleaseCandidateVerifyOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) json_output: bool,
}

pub(super) struct PluginReleaseCandidateWindowsRecoveryOptions {
    pub(super) package_summary: PathBuf,
    pub(super) package_summary_sha256: String,
    pub(super) package_archive: PathBuf,
    pub(super) package_archive_sha256: String,
    pub(super) distribution_rehearsal: PathBuf,
    pub(super) distribution_rehearsal_sha256: String,
    pub(super) adapter_observer_bundle: PathBuf,
    pub(super) adapter_observer_bundle_sha256: String,
    pub(super) adapter_observer_archive: PathBuf,
    pub(super) adapter_observer_archive_sha256: String,
    pub(super) adapter_install_smoke_observer_bundle: PathBuf,
    pub(super) adapter_install_smoke_observer_bundle_sha256: String,
    pub(super) adapter_install_smoke_observer_archive: PathBuf,
    pub(super) adapter_install_smoke_observer_archive_sha256: String,
    pub(super) consumer_lifecycle_observer_bundle: PathBuf,
    pub(super) consumer_lifecycle_observer_bundle_sha256: String,
    pub(super) consumer_lifecycle_observer_archive: PathBuf,
    pub(super) consumer_lifecycle_observer_archive_sha256: String,
    pub(super) release_gate_with_replacement_observer_bundle: PathBuf,
    pub(super) release_gate_with_replacement_observer_bundle_sha256: String,
    pub(super) release_gate_with_replacement_observer_archive: PathBuf,
    pub(super) release_gate_with_replacement_observer_archive_sha256: String,
    pub(super) control_plane_fixture_handoff_verification: PathBuf,
    pub(super) control_plane_fixture_handoff_verification_sha256: String,
    pub(super) control_plane_readback_commit: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginReleaseCandidateWindowsRecoveryVerifyOptions {
    pub(super) recovery: PathBuf,
    pub(super) recovery_sha256: String,
    pub(super) out: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginReleaseCandidateWindowsTransferBundleOptions {
    pub(super) ao2_source_archive: PathBuf,
    pub(super) ao2_source_archive_sha256: String,
    pub(super) recovery_dir: PathBuf,
    pub(super) recovery: PathBuf,
    pub(super) recovery_sha256: String,
    pub(super) recovery_verification: PathBuf,
    pub(super) recovery_verification_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginReleaseCandidateObserverBundleOptions {
    pub(super) macos_verification: PathBuf,
    pub(super) macos_sha256: String,
    pub(super) ubuntu_verification: PathBuf,
    pub(super) ubuntu_sha256: String,
    pub(super) windows_verification: PathBuf,
    pub(super) windows_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginReleaseCandidateObserverBundleVerifyOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) archive: PathBuf,
    pub(super) archive_sha256: String,
    pub(super) json_output: bool,
}

pub(super) struct PluginPulseApplyObserverBundleOptions {
    pub(super) macos_apply_result: PathBuf,
    pub(super) macos_sha256: String,
    pub(super) ubuntu_apply_result: PathBuf,
    pub(super) ubuntu_sha256: String,
    pub(super) windows_apply_result: Option<PathBuf>,
    pub(super) windows_sha256: Option<String>,
    pub(super) windows_unavailable_reason: Option<String>,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginPulseApplyObserverBundleVerifyOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) archive: PathBuf,
    pub(super) archive_sha256: String,
    pub(super) json_output: bool,
}

pub(super) struct PluginPulseOnceObserverBundleOptions {
    pub(super) macos_once: PathBuf,
    pub(super) macos_sha256: String,
    pub(super) ubuntu_once: PathBuf,
    pub(super) ubuntu_sha256: String,
    pub(super) windows_once: PathBuf,
    pub(super) windows_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginPulseOnceObserverBundleVerifyOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) archive: PathBuf,
    pub(super) archive_sha256: String,
    pub(super) json_output: bool,
}

pub(super) struct PluginPulseChainObserverBundleOptions {
    pub(super) macos_chain: PathBuf,
    pub(super) macos_sha256: String,
    pub(super) ubuntu_chain: PathBuf,
    pub(super) ubuntu_sha256: String,
    pub(super) windows_chain: PathBuf,
    pub(super) windows_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginPulseChainObserverBundleVerifyOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) archive: PathBuf,
    pub(super) archive_sha256: String,
    pub(super) json_output: bool,
}

pub(super) struct PluginPulseEvalLoopObserverBundleOptions {
    pub(super) macos_eval_loop: PathBuf,
    pub(super) macos_sha256: String,
    pub(super) ubuntu_eval_loop: PathBuf,
    pub(super) ubuntu_sha256: String,
    pub(super) windows_eval_loop: PathBuf,
    pub(super) windows_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginPulseEvalLoopObserverBundleVerifyOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) archive: PathBuf,
    pub(super) archive_sha256: String,
    pub(super) json_output: bool,
}

pub(super) struct PluginPulseExecutorObserverBundleOptions {
    pub(super) macos_executor: PathBuf,
    pub(super) macos_sha256: String,
    pub(super) ubuntu_executor: PathBuf,
    pub(super) ubuntu_sha256: String,
    pub(super) windows_executor: PathBuf,
    pub(super) windows_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginPulseExecutorObserverBundleVerifyOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) archive: PathBuf,
    pub(super) archive_sha256: String,
    pub(super) json_output: bool,
}

pub(super) struct PluginPulseApplyWindowsRecoveryOptions {
    pub(super) apply_result: PathBuf,
    pub(super) apply_result_sha256: String,
    pub(super) observer_bundle: PathBuf,
    pub(super) observer_bundle_sha256: String,
    pub(super) observer_archive: PathBuf,
    pub(super) observer_archive_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginReleaseCandidateControlPlaneFixtureHandoffOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) archive: PathBuf,
    pub(super) archive_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginReleaseCandidateControlPlaneFixtureHandoffVerifyOptions {
    pub(super) handoff: PathBuf,
    pub(super) handoff_sha256: String,
    pub(super) out: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginFinalInstallTranscriptOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) archive: PathBuf,
    pub(super) archive_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginFinalInstallTranscriptObserverBundleOptions {
    pub(super) macos_codex_transcript: PathBuf,
    pub(super) macos_codex_sha256: String,
    pub(super) macos_claude_transcript: PathBuf,
    pub(super) macos_claude_sha256: String,
    pub(super) ubuntu_codex_transcript: PathBuf,
    pub(super) ubuntu_codex_sha256: String,
    pub(super) ubuntu_claude_transcript: PathBuf,
    pub(super) ubuntu_claude_sha256: String,
    pub(super) windows_codex_transcript: PathBuf,
    pub(super) windows_codex_sha256: String,
    pub(super) windows_claude_transcript: PathBuf,
    pub(super) windows_claude_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginShipmentReadinessOptions {
    pub(super) package_summary: PathBuf,
    pub(super) package_summary_sha256: String,
    pub(super) package_archive: PathBuf,
    pub(super) package_archive_sha256: String,
    pub(super) adapter_observer_bundle: PathBuf,
    pub(super) adapter_observer_bundle_sha256: String,
    pub(super) adapter_observer_archive: PathBuf,
    pub(super) adapter_observer_archive_sha256: String,
    pub(super) adapter_install_smoke_observer_bundle: PathBuf,
    pub(super) adapter_install_smoke_observer_bundle_sha256: String,
    pub(super) adapter_install_smoke_observer_archive: PathBuf,
    pub(super) adapter_install_smoke_observer_archive_sha256: String,
    pub(super) consumer_lifecycle_observer_bundle: PathBuf,
    pub(super) consumer_lifecycle_observer_bundle_sha256: String,
    pub(super) consumer_lifecycle_observer_archive: PathBuf,
    pub(super) consumer_lifecycle_observer_archive_sha256: String,
    pub(super) release_candidate_observer_bundle: PathBuf,
    pub(super) release_candidate_observer_bundle_sha256: String,
    pub(super) release_candidate_observer_archive: PathBuf,
    pub(super) release_candidate_observer_archive_sha256: String,
    pub(super) final_install_transcript_observer_bundle: PathBuf,
    pub(super) final_install_transcript_observer_bundle_sha256: String,
    pub(super) final_install_transcript_observer_archive: PathBuf,
    pub(super) final_install_transcript_observer_archive_sha256: String,
    pub(super) control_plane_readback_commit: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginControlPlaneFixtureHandoffOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) archive: PathBuf,
    pub(super) archive_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginControlPlaneFixtureHandoffVerifyOptions {
    pub(super) handoff: PathBuf,
    pub(super) handoff_sha256: String,
    pub(super) out: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginDistributionObserverBundleOptions {
    pub(super) macos_observer: PathBuf,
    pub(super) macos_sha256: String,
    pub(super) ubuntu_observer: PathBuf,
    pub(super) ubuntu_sha256: String,
    pub(super) windows_observer: PathBuf,
    pub(super) windows_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginCleanPackageOperatorIndexOptions {
    pub(super) macos_rehearsal: PathBuf,
    pub(super) macos_sha256: String,
    pub(super) ubuntu_rehearsal: PathBuf,
    pub(super) ubuntu_sha256: String,
    pub(super) windows_rehearsal: PathBuf,
    pub(super) windows_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginPackagedReplacementObserverBundleOptions {
    pub(super) macos_proof: PathBuf,
    pub(super) macos_sha256: String,
    pub(super) ubuntu_proof: PathBuf,
    pub(super) ubuntu_sha256: String,
    pub(super) windows_proof: PathBuf,
    pub(super) windows_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginPackagedReplacementObserverBundleVerifyOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) archive: PathBuf,
    pub(super) archive_sha256: String,
    pub(super) json_output: bool,
}

pub(super) struct PluginReleaseGateWithReplacementObserverBundleOptions {
    pub(super) macos_rollup: PathBuf,
    pub(super) macos_sha256: String,
    pub(super) ubuntu_rollup: PathBuf,
    pub(super) ubuntu_sha256: String,
    pub(super) windows_rollup: PathBuf,
    pub(super) windows_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginAdapterScaffoldOptions {
    pub(super) package_summary: PathBuf,
    pub(super) package_summary_sha256: String,
    pub(super) package_archive: PathBuf,
    pub(super) package_archive_sha256: String,
    pub(super) k37_bundle: PathBuf,
    pub(super) k37_bundle_sha256: String,
    pub(super) k37_archive: PathBuf,
    pub(super) k37_archive_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginAdapterScaffoldVerifyOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) json_output: bool,
}

pub(super) struct PluginAdapterInstallSmokeOptions {
    pub(super) summary: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) out: Option<PathBuf>,
    pub(super) json_output: bool,
}

pub(super) struct PluginAdapterInstallSmokeVerifyOptions {
    pub(super) smoke: PathBuf,
    pub(super) smoke_sha256: String,
    pub(super) json_output: bool,
}

pub(super) struct PluginAdapterInstallSmokeObserverBundleOptions {
    pub(super) macos_verification: PathBuf,
    pub(super) macos_sha256: String,
    pub(super) ubuntu_verification: PathBuf,
    pub(super) ubuntu_sha256: String,
    pub(super) windows_verification: PathBuf,
    pub(super) windows_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginAdapterObserverBundleOptions {
    pub(super) macos_verification: PathBuf,
    pub(super) macos_sha256: String,
    pub(super) ubuntu_verification: PathBuf,
    pub(super) ubuntu_sha256: String,
    pub(super) windows_verification: PathBuf,
    pub(super) windows_sha256: String,
    pub(super) out_dir: PathBuf,
    pub(super) json_output: bool,
}

pub(super) struct PluginWrapperHarnessVerifyOptions {
    pub(super) evidence_dir: PathBuf,
    pub(super) summary_sha256: String,
    pub(super) json_output: bool,
}
